version: '3.2'

services:
  configurationservice:
    image: patrykks/iosr-configuration-service
    ports:
      - "7777"

  eureka:
    image: patrykks/iosr-discovery-service
    ports:
      - "8761"
    depends_on:
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777

  excelexportservice:
    image: patrykks/iosr-excel-export-service
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    ports:
      - "4444"